server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.72.132
    port: 6379
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.72.132:3306/guli_cart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.72.132
    port: 5672
    virtual-host: /leo
    username: leonardo
    password: leonardo
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 4
        prefetch: 1
feign:
  sentinel:
    enabled: true


auth:
  jwt:
    pubKeyPath: E:/_Code_/atguigu/20 gmall/gmall-0821/rsa/rsa.pub
    cookieName: GMALL-TOKEN
    userKey: userKey
    expireTime: 15552000 # userKey的过期时间
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml