server:
  port: 18091
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://192.168.72.132:18888/xxl-job-admin
    executor:
      address: ''
      appname: gmall-price-synchrnization-executor
      ip: ''
      logpath: data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
spring:
  datasource:
    url: jdbc:mysql://192.168.72.132:3306/guli_cart
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.72.132

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
