server:
  port: 18088


spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8080
    sentinel:
      transport:
        dashboard: localhost:8848
        port: 8719
  zipkin:
    discovery-client-enabled: false
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.72.132
feign:
  sentinel:
    enabled: true

logging:
  level:
    root: debug